FROM php:8.2-apache

LABEL maintainer="tu-email@ejemplo.com"

# Instalar utilidades mínimas
RUN apt-get update && apt-get install -y --no-install-recommends \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Copiar la app (index.php) al directorio web
COPY index.php /var/www/html/index.php

# Ajustes de permisos
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Exponer puerto 80
EXPOSE 80
